spring.mvc.view.prefix: /WEB-INF/content/
spring.mvc.view.suffix: .jsp
logging:
  level:
    root: DEBUG
    org:
      apache:
        tomcat: INFO
#struts:
#  convention:
#    exclude:
#      parentClassLoader: "false"
#    action:
#      fileProtocols: "jar,code-source"